<?php

namespace app\models\opisi;

use Yii;

/**
 * This is the model class for table "region_fond_name".
 *
 * @property int $id
 * @property string $fond_name
 * @property int $tag_link_id
 */
class RegionFondName extends \yii\db\ActiveRecord
{
    public $tags;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'region_fond_name';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
//            [['tag_link_id'], 'integer'],
            [['fond_name'], 'string', 'max' => 100],
            [['tags'], 'safe']
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fond_name' => 'Fond Name',
//            'tag_link_id' => 'Tag Link ID',
            'tags' => 'Tagz',
            'tagsString' => 'Теги',
        ];
    }

//    public function getFondTags(){
//        return $this->hasMany(RegionTagLink::className(),['fond_name_id' => 'id']);
//    }
//    public function getRegionTagLink(){
//        return $this->hasMany(RegionTagLink::className(),['id' => 'fond_name_id']);
//    }
//
//    public function getTags(){
//        return $this->hasMany(RegionTagName::className(),['id' => 'fond_name_id'])->via('regionTagLink');
//    }


    public function getTagNames()
    {
        return $this->hasMany(RegionTagName::className(), ['id' => 'tag_id'])
            ->viaTable(RegionTagLink::tableName(), ['fond_name_id' => 'id']);
    }

    public function getTagsString()
    {
        $arr = \yii\helpers\ArrayHelper::map($this->tags,'id', 'tag_name');

        return implode(", ", $arr);
    }

    public function afterFind()
    {
        $this->tags = $this->tagNames;
    }



    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        RegionTagLink::deleteAll('fond_name_id = '.$this->id.'');

        foreach ($this->tags as $tag)
        {
            $model = new RegionTagLink();
                $model->fond_name_id = $this->id;
                $model->tag_id = $tag;

            $model->save();
        }
    }
}
