<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 01.05.2020
 * Time: 0:31
 */

namespace app\models\sbu;

class KgbFond extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'kgb_fond'; // TODO: Change the autogenerated stub
    }


}